const companies = [
  {
    companyId: 'cmp-ecotech-corp',
    name: 'EcoTech Corp',
    slug: 'ecotech-corp',
    type: 'buyer',
    country: 'United States',
    region: 'California',
    description: 'Enterprise sustainability team offsetting operations across North America.',
    badges: ['Top Buyer 2024', 'Science Based Targets'],
    metrics: {
      totalCo2OffsetTons: 1040,
      activeCredits: 150,
      retiredCredits: 75,
      totalInvestedUsd: 5625,
    },
    purchasedCredits: [
      {
        projectName: 'Amazon Rainforest Conservation',
        projectType: 'Forest Protection',
        tons: 50,
        pricePerTonUsd: 25,
        purchaseDate: new Date('2024-01-15'),
        status: 'active',
        tokenId: 'TKN-001234',
        verifier: 'Verra',
      },
      {
        projectName: 'Solar Farm Development',
        projectType: 'Renewable Energy',
        tons: 75,
        pricePerTonUsd: 22,
        purchaseDate: new Date('2024-01-20'),
        status: 'retired',
        tokenId: 'TKN-001235',
        verifier: 'Gold Standard',
      },
      {
        projectName: 'Wind Power Initiative',
        projectType: 'Renewable Energy',
        tons: 100,
        pricePerTonUsd: 28,
        purchaseDate: new Date('2024-02-10'),
        status: 'active',
        tokenId: 'TKN-001236',
        verifier: 'CDM',
      },
    ],
    retirementRecords: [
      {
        tokenId: 'TKN-001235',
        projectName: 'Solar Farm Development',
        tonsRetired: 75,
        retiredDate: new Date('2024-01-28'),
        transactionHash: '0xef12...34cd',
        certificateId: 'CERT-2024-001235',
        verifier: 'Gold Standard',
        ipfsHash: 'QmA1B...C456',
      },
      {
        tokenId: 'TKN-001240',
        projectName: 'Mangrove Restoration',
        tonsRetired: 40,
        retiredDate: new Date('2024-02-12'),
        transactionHash: '0x9876...abcd',
        certificateId: 'CERT-2024-001240',
        verifier: 'Verra',
        ipfsHash: 'QmX5Y...Z789',
      },
    ],
    transactions: [
      {
        transactionType: 'mint',
        tokenId: 'TKN-001234',
        projectName: 'Amazon Rainforest Conservation',
        amountTons: 50,
        from: 'GreenVerifier Alliance',
        to: 'EcoTech Corp',
        transactionHash: '0xmint123',
        occurredAt: new Date('2024-01-10'),
      },
      {
        transactionType: 'transfer',
        tokenId: 'TKN-001236',
        projectName: 'Wind Power Initiative',
        amountTons: 100,
        from: 'GreenVerifier Alliance',
        to: 'EcoTech Corp',
        transactionHash: '0xtransfer456',
        occurredAt: new Date('2024-02-05'),
      },
      {
        transactionType: 'retire',
        tokenId: 'TKN-001235',
        projectName: 'Solar Farm Development',
        amountTons: 75,
        from: 'EcoTech Corp',
        to: 'Retired',
        transactionHash: '0xretire789',
        occurredAt: new Date('2024-01-28'),
      },
      {
        transactionType: 'retire',
        tokenId: 'TKN-001240',
        projectName: 'Mangrove Restoration',
        amountTons: 40,
        from: 'EcoTech Corp',
        to: 'Retired',
        transactionHash: '0xretire990',
        occurredAt: new Date('2024-02-12'),
      },
    ],
  },
  {
    companyId: 'cmp-greenverifier-alliance',
    name: 'GreenVerifier Alliance',
    slug: 'greenverifier-alliance',
    type: 'verifier',
    country: 'Brazil',
    region: 'Acre',
    description: 'Verifier consortium overseeing forest and renewable energy projects.',
    badges: ['Verified Partner', 'ISO 14065'],
    verifierMetrics: {
      totalProjects: 12,
      creditsIssued: 125000,
      creditsSold: 83000,
      revenueUsd: 2650000,
    },
    projects: [
      {
        name: 'Amazon Rainforest Conservation',
        description: 'Protecting 50,000 hectares of pristine Amazon rainforest.',
        projectType: 'Forest Protection',
        country: 'Brazil',
        region: 'Acre State',
        location: 'Acre, Brazil',
        totalCredits: 1200,
        soldCredits: 600,
        tonsAvailable: 600,
        pricePerTonUsd: 25,
        vintage: '2024',
        status: 'active',
        verifierRegistry: 'Verra',
        listingImageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=400&h=300&fit=crop',
        addedDate: new Date('2024-01-05'),
      },
      {
        name: 'Mangrove Restoration',
        description: 'Restoring coastal mangrove ecosystems for biodiversity.',
        projectType: 'Forest Protection',
        country: 'Indonesia',
        region: 'Sumatra',
        location: 'North Sumatra, Indonesia',
        totalCredits: 900,
        soldCredits: 260,
        tonsAvailable: 640,
        pricePerTonUsd: 30,
        vintage: '2024',
        status: 'active',
        verifierRegistry: 'Verra',
        listingImageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop',
        addedDate: new Date('2024-01-12'),
      },
      {
        name: 'Wind Power Initiative',
        description: 'Offshore wind farm generating sustainable electricity.',
        projectType: 'Renewable Energy',
        country: 'Denmark',
        region: 'Jutland',
        location: 'Jutland Peninsula, Denmark',
        totalCredits: 950,
        soldCredits: 400,
        tonsAvailable: 550,
        pricePerTonUsd: 28,
        vintage: '2024',
        status: 'active',
        verifierRegistry: 'Gold Standard',
        listingImageUrl: 'https://images.unsplash.com/photo-1532601224476-15c79f2f7a51?w=400&h=300&fit=crop',
        addedDate: new Date('2024-02-02'),
      },
    ],
    transactions: [
      {
        transactionType: 'mint',
        tokenId: 'TKN-001234',
        projectName: 'Amazon Rainforest Conservation',
        amountTons: 600,
        from: 'Project Registry',
        to: 'GreenVerifier Alliance',
        transactionHash: '0xmint-verifier-01',
        occurredAt: new Date('2024-01-01'),
      },
      {
        transactionType: 'mint',
        tokenId: 'TKN-001236',
        projectName: 'Wind Power Initiative',
        amountTons: 550,
        from: 'Project Registry',
        to: 'GreenVerifier Alliance',
        transactionHash: '0xmint-verifier-02',
        occurredAt: new Date('2024-02-01'),
      },
    ],
  },
  {
    companyId: 'cmp-sustainable-innovations',
    name: 'Sustainable Innovations',
    slug: 'sustainable-innovations',
    type: 'both',
    country: 'India',
    region: 'Rajasthan',
    description: 'Hybrid verifier and buyer driving renewable projects across Asia.',
    badges: ['Renewable Pioneer', 'Top Seller 2023'],
    metrics: {
      totalCo2OffsetTons: 620,
      activeCredits: 95,
      retiredCredits: 45,
      totalInvestedUsd: 2310,
    },
    verifierMetrics: {
      totalProjects: 6,
      creditsIssued: 54000,
      creditsSold: 31000,
      revenueUsd: 940000,
    },
    purchasedCredits: [
      {
        projectName: 'Hydroelectric Development',
        projectType: 'Renewable Energy',
        tons: 60,
        pricePerTonUsd: 26,
        purchaseDate: new Date('2024-01-30'),
        status: 'active',
        tokenId: 'TKN-001238',
        verifier: 'Gold Standard',
      },
      {
        projectName: 'Reforestation Program',
        projectType: 'Forest Protection',
        tons: 35,
        pricePerTonUsd: 24,
        purchaseDate: new Date('2024-02-08'),
        status: 'active',
        tokenId: 'TKN-001239',
        verifier: 'CDM',
      },
    ],
    retirementRecords: [
      {
        tokenId: 'TKN-001237',
        projectName: 'Community Solar Initiative',
        tonsRetired: 30,
        retiredDate: new Date('2024-01-18'),
        transactionHash: '0xsolar-retire-01',
        certificateId: 'CERT-2024-001237',
        verifier: 'Gold Standard',
        ipfsHash: 'QmSOLAR...123',
      },
    ],
    projects: [
      {
        name: 'Solar Farm Development',
        description: '100MW solar installation providing clean energy.',
        projectType: 'Renewable Energy',
        country: 'India',
        region: 'Rajasthan',
        location: 'Jaisalmer, India',
        totalCredits: 800,
        soldCredits: 420,
        tonsAvailable: 380,
        pricePerTonUsd: 22,
        vintage: '2024',
        status: 'active',
        verifierRegistry: 'Gold Standard',
        listingImageUrl: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&h=300&fit=crop',
        addedDate: new Date('2024-01-20'),
      },
    ],
    transactions: [
      {
        transactionType: 'mint',
        tokenId: 'TKN-001237',
        projectName: 'Community Solar Initiative',
        amountTons: 300,
        from: 'Project Registry',
        to: 'Sustainable Innovations',
        transactionHash: '0xmint-solar-01',
        occurredAt: new Date('2024-01-05'),
      },
      {
        transactionType: 'retire',
        tokenId: 'TKN-001237',
        projectName: 'Community Solar Initiative',
        amountTons: 30,
        from: 'Sustainable Innovations',
        to: 'Retired',
        transactionHash: '0xsolar-retire-01',
        occurredAt: new Date('2024-01-18'),
      },
      {
        transactionType: 'transfer',
        tokenId: 'TKN-001238',
        projectName: 'Hydroelectric Development',
        amountTons: 60,
        from: 'GreenVerifier Alliance',
        to: 'Sustainable Innovations',
        transactionHash: '0xtransfer-hydro-01',
        occurredAt: new Date('2024-01-30'),
      },
    ],
  },
]

export default companies
